# Target specific macros
TARGET = BRO_Client
TARGET_SOURCES := \
	BRO_spam_client.c \
	BRO_spam_pid.c \
	BRO_spam_fists.c 
TOPPERS_OSEK_OIL_SOURCE := ./BRO_spam_client.oil

O_PATH ?= build

include ../../spamOSEK/ecrobot/ecrobot.mak

